/*
 * XI Sdk Resellers
 *
 * For Resellers seeking to innovate with Ingram Micro API solutions, automate your eCommerce experience with our array of APIs and webhooks to craft a seamless journey for your customers.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using xi.sdk.resellers.Model;
using xi.sdk.resellers.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace xi.sdk.resellers.Test.Model
{
    /// <summary>
    ///  Class for testing AvailabilityAsyncNotificationRequestResourceInner
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AvailabilityAsyncNotificationRequestResourceInnerTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for AvailabilityAsyncNotificationRequestResourceInner
        //private AvailabilityAsyncNotificationRequestResourceInner instance;

        public AvailabilityAsyncNotificationRequestResourceInnerTests()
        {
            // TODO uncomment below to create an instance of AvailabilityAsyncNotificationRequestResourceInner
            //instance = new AvailabilityAsyncNotificationRequestResourceInner();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AvailabilityAsyncNotificationRequestResourceInner
        /// </summary>
        [Fact]
        public void AvailabilityAsyncNotificationRequestResourceInnerInstanceTest()
        {
            // TODO uncomment below to test "IsType" AvailabilityAsyncNotificationRequestResourceInner
            //Assert.IsType<AvailabilityAsyncNotificationRequestResourceInner>(instance);
        }

        /// <summary>
        /// Test the property 'EventType'
        /// </summary>
        [Fact]
        public void EventTypeTest()
        {
            // TODO unit test for the property 'EventType'
        }

        /// <summary>
        /// Test the property 'IngramPartNumber'
        /// </summary>
        [Fact]
        public void IngramPartNumberTest()
        {
            // TODO unit test for the property 'IngramPartNumber'
        }

        /// <summary>
        /// Test the property 'VendorPartNumber'
        /// </summary>
        [Fact]
        public void VendorPartNumberTest()
        {
            // TODO unit test for the property 'VendorPartNumber'
        }

        /// <summary>
        /// Test the property 'VendorName'
        /// </summary>
        [Fact]
        public void VendorNameTest()
        {
            // TODO unit test for the property 'VendorName'
        }

        /// <summary>
        /// Test the property 'UpcCode'
        /// </summary>
        [Fact]
        public void UpcCodeTest()
        {
            // TODO unit test for the property 'UpcCode'
        }

        /// <summary>
        /// Test the property 'SkuStatus'
        /// </summary>
        [Fact]
        public void SkuStatusTest()
        {
            // TODO unit test for the property 'SkuStatus'
        }

        /// <summary>
        /// Test the property 'BackOrderFlag'
        /// </summary>
        [Fact]
        public void BackOrderFlagTest()
        {
            // TODO unit test for the property 'BackOrderFlag'
        }

        /// <summary>
        /// Test the property 'TotalAvailability'
        /// </summary>
        [Fact]
        public void TotalAvailabilityTest()
        {
            // TODO unit test for the property 'TotalAvailability'
        }

        /// <summary>
        /// Test the property 'Links'
        /// </summary>
        [Fact]
        public void LinksTest()
        {
            // TODO unit test for the property 'Links'
        }
    }
}
