/*
 * XI Sdk Resellers
 *
 * For Resellers seeking to innovate with Ingram Micro API solutions, automate your eCommerce experience with our array of API's and webhooks to craft a seamless journey for your customers.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using xi.sdk.resellers.Model;
using xi.sdk.resellers.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace xi.sdk.resellers.Test.Model
{
    /// <summary>
    ///  Class for testing DealsDetailsResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DealsDetailsResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for DealsDetailsResponse
        //private DealsDetailsResponse instance;

        public DealsDetailsResponseTests()
        {
            // TODO uncomment below to create an instance of DealsDetailsResponse
            //instance = new DealsDetailsResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of DealsDetailsResponse
        /// </summary>
        [Fact]
        public void DealsDetailsResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" DealsDetailsResponse
            //Assert.IsType<DealsDetailsResponse>(instance);
        }

        /// <summary>
        /// Test the property 'DealId'
        /// </summary>
        [Fact]
        public void DealIdTest()
        {
            // TODO unit test for the property 'DealId'
        }

        /// <summary>
        /// Test the property 'VarVersion'
        /// </summary>
        [Fact]
        public void VarVersionTest()
        {
            // TODO unit test for the property 'VarVersion'
        }

        /// <summary>
        /// Test the property 'EndUser'
        /// </summary>
        [Fact]
        public void EndUserTest()
        {
            // TODO unit test for the property 'EndUser'
        }

        /// <summary>
        /// Test the property 'ExtendedMsrp'
        /// </summary>
        [Fact]
        public void ExtendedMsrpTest()
        {
            // TODO unit test for the property 'ExtendedMsrp'
        }

        /// <summary>
        /// Test the property 'Vendor'
        /// </summary>
        [Fact]
        public void VendorTest()
        {
            // TODO unit test for the property 'Vendor'
        }

        /// <summary>
        /// Test the property 'DealReceivedOn'
        /// </summary>
        [Fact]
        public void DealReceivedOnTest()
        {
            // TODO unit test for the property 'DealReceivedOn'
        }

        /// <summary>
        /// Test the property 'DealExpiryDate'
        /// </summary>
        [Fact]
        public void DealExpiryDateTest()
        {
            // TODO unit test for the property 'DealExpiryDate'
        }

        /// <summary>
        /// Test the property 'PriceProtectionEndDate'
        /// </summary>
        [Fact]
        public void PriceProtectionEndDateTest()
        {
            // TODO unit test for the property 'PriceProtectionEndDate'
        }

        /// <summary>
        /// Test the property 'CurrencyCode'
        /// </summary>
        [Fact]
        public void CurrencyCodeTest()
        {
            // TODO unit test for the property 'CurrencyCode'
        }

        /// <summary>
        /// Test the property 'EndUserInfo'
        /// </summary>
        [Fact]
        public void EndUserInfoTest()
        {
            // TODO unit test for the property 'EndUserInfo'
        }

        /// <summary>
        /// Test the property 'Products'
        /// </summary>
        [Fact]
        public void ProductsTest()
        {
            // TODO unit test for the property 'Products'
        }
    }
}
