/*
 * XI Sdk Resellers
 *
 * For Resellers seeking to innovate with Ingram Micro API solutions, automate your eCommerce experience with our array of API's and webhooks to craft a seamless journey for your customers.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using xi.sdk.resellers.Model;
using xi.sdk.resellers.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace xi.sdk.resellers.Test.Model
{
    /// <summary>
    ///  Class for testing FreightRequestLinesInner
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class FreightRequestLinesInnerTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for FreightRequestLinesInner
        //private FreightRequestLinesInner instance;

        public FreightRequestLinesInnerTests()
        {
            // TODO uncomment below to create an instance of FreightRequestLinesInner
            //instance = new FreightRequestLinesInner();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of FreightRequestLinesInner
        /// </summary>
        [Fact]
        public void FreightRequestLinesInnerInstanceTest()
        {
            // TODO uncomment below to test "IsType" FreightRequestLinesInner
            //Assert.IsType<FreightRequestLinesInner>(instance);
        }

        /// <summary>
        /// Test the property 'CustomerLineNumber'
        /// </summary>
        [Fact]
        public void CustomerLineNumberTest()
        {
            // TODO unit test for the property 'CustomerLineNumber'
        }

        /// <summary>
        /// Test the property 'IngramPartNumber'
        /// </summary>
        [Fact]
        public void IngramPartNumberTest()
        {
            // TODO unit test for the property 'IngramPartNumber'
        }

        /// <summary>
        /// Test the property 'Quantity'
        /// </summary>
        [Fact]
        public void QuantityTest()
        {
            // TODO unit test for the property 'Quantity'
        }

        /// <summary>
        /// Test the property 'WarehouseId'
        /// </summary>
        [Fact]
        public void WarehouseIdTest()
        {
            // TODO unit test for the property 'WarehouseId'
        }

        /// <summary>
        /// Test the property 'CarrierCode'
        /// </summary>
        [Fact]
        public void CarrierCodeTest()
        {
            // TODO unit test for the property 'CarrierCode'
        }
    }
}
