/*
 * XI Sdk Resellers
 *
 * For Resellers seeking to innovate with Ingram Micro API solutions, automate your eCommerce experience with our array of APIs and webhooks to craft a seamless journey for your customers.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using xi.sdk.resellers.Model;
using xi.sdk.resellers.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace xi.sdk.resellers.Test.Model
{
    /// <summary>
    ///  Class for testing InvoiceSearchResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class InvoiceSearchResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for InvoiceSearchResponse
        //private InvoiceSearchResponse instance;

        public InvoiceSearchResponseTests()
        {
            // TODO uncomment below to create an instance of InvoiceSearchResponse
            //instance = new InvoiceSearchResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of InvoiceSearchResponse
        /// </summary>
        [Fact]
        public void InvoiceSearchResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" InvoiceSearchResponse
            //Assert.IsType<InvoiceSearchResponse>(instance);
        }

        /// <summary>
        /// Test the property 'RecordsFound'
        /// </summary>
        [Fact]
        public void RecordsFoundTest()
        {
            // TODO unit test for the property 'RecordsFound'
        }

        /// <summary>
        /// Test the property 'PageSize'
        /// </summary>
        [Fact]
        public void PageSizeTest()
        {
            // TODO unit test for the property 'PageSize'
        }

        /// <summary>
        /// Test the property 'PageNumber'
        /// </summary>
        [Fact]
        public void PageNumberTest()
        {
            // TODO unit test for the property 'PageNumber'
        }

        /// <summary>
        /// Test the property 'Invoices'
        /// </summary>
        [Fact]
        public void InvoicesTest()
        {
            // TODO unit test for the property 'Invoices'
        }

        /// <summary>
        /// Test the property 'NextPage'
        /// </summary>
        [Fact]
        public void NextPageTest()
        {
            // TODO unit test for the property 'NextPage'
        }
    }
}
