/*
 * XI Sdk Resellers
 *
 * For Resellers seeking to innovate with Ingram Micro API solutions, automate your eCommerce experience with our array of API's and webhooks to craft a seamless journey for your customers.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using xi.sdk.resellers.Model;
using xi.sdk.resellers.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace xi.sdk.resellers.Test.Model
{
    /// <summary>
    ///  Class for testing InvoiceDetailsv61ResponseSummaryMiscChargesInner
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class InvoiceDetailsv61ResponseSummaryMiscChargesInnerTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for InvoiceDetailsv61ResponseSummaryMiscChargesInner
        //private InvoiceDetailsv61ResponseSummaryMiscChargesInner instance;

        public InvoiceDetailsv61ResponseSummaryMiscChargesInnerTests()
        {
            // TODO uncomment below to create an instance of InvoiceDetailsv61ResponseSummaryMiscChargesInner
            //instance = new InvoiceDetailsv61ResponseSummaryMiscChargesInner();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of InvoiceDetailsv61ResponseSummaryMiscChargesInner
        /// </summary>
        [Fact]
        public void InvoiceDetailsv61ResponseSummaryMiscChargesInnerInstanceTest()
        {
            // TODO uncomment below to test "IsType" InvoiceDetailsv61ResponseSummaryMiscChargesInner
            //Assert.IsType<InvoiceDetailsv61ResponseSummaryMiscChargesInner>(instance);
        }

        /// <summary>
        /// Test the property 'ChargeDescription'
        /// </summary>
        [Fact]
        public void ChargeDescriptionTest()
        {
            // TODO unit test for the property 'ChargeDescription'
        }

        /// <summary>
        /// Test the property 'MiscChargeLineCount'
        /// </summary>
        [Fact]
        public void MiscChargeLineCountTest()
        {
            // TODO unit test for the property 'MiscChargeLineCount'
        }

        /// <summary>
        /// Test the property 'MiscChargeLineTotal'
        /// </summary>
        [Fact]
        public void MiscChargeLineTotalTest()
        {
            // TODO unit test for the property 'MiscChargeLineTotal'
        }

        /// <summary>
        /// Test the property 'ChargeLineReference'
        /// </summary>
        [Fact]
        public void ChargeLineReferenceTest()
        {
            // TODO unit test for the property 'ChargeLineReference'
        }

        /// <summary>
        /// Test the property 'IsNonMisc'
        /// </summary>
        [Fact]
        public void IsNonMiscTest()
        {
            // TODO unit test for the property 'IsNonMisc'
        }
    }
}
