/*
 * XI Sdk Resellers
 *
 * For Resellers seeking to innovate with Ingram Micro API solutions, automate your eCommerce experience with our array of API's and webhooks to craft a seamless journey for your customers.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using xi.sdk.resellers.Model;
using xi.sdk.resellers.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace xi.sdk.resellers.Test.Model
{
    /// <summary>
    ///  Class for testing InvoiceDetailsv61ResponseSummaryLines
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class InvoiceDetailsv61ResponseSummaryLinesTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for InvoiceDetailsv61ResponseSummaryLines
        //private InvoiceDetailsv61ResponseSummaryLines instance;

        public InvoiceDetailsv61ResponseSummaryLinesTests()
        {
            // TODO uncomment below to create an instance of InvoiceDetailsv61ResponseSummaryLines
            //instance = new InvoiceDetailsv61ResponseSummaryLines();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of InvoiceDetailsv61ResponseSummaryLines
        /// </summary>
        [Fact]
        public void InvoiceDetailsv61ResponseSummaryLinesInstanceTest()
        {
            // TODO uncomment below to test "IsType" InvoiceDetailsv61ResponseSummaryLines
            //Assert.IsType<InvoiceDetailsv61ResponseSummaryLines>(instance);
        }

        /// <summary>
        /// Test the property 'ProductLineCount'
        /// </summary>
        [Fact]
        public void ProductLineCountTest()
        {
            // TODO unit test for the property 'ProductLineCount'
        }

        /// <summary>
        /// Test the property 'ProductLineTotalQuantity'
        /// </summary>
        [Fact]
        public void ProductLineTotalQuantityTest()
        {
            // TODO unit test for the property 'ProductLineTotalQuantity'
        }
    }
}
