/*
 * XI Sdk Resellers
 *
 * For Resellers seeking to innovate with Ingram Micro API solutions, automate your eCommerce experience with our array of APIs and webhooks to craft a seamless journey for your customers.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using xi.sdk.resellers.Model;
using xi.sdk.resellers.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace xi.sdk.resellers.Test.Model
{
    /// <summary>
    ///  Class for testing OrderDetailB2BLinesInnerShipmentDetailsInnerCarrierDetailsInnerTrackingDetailsInner
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class OrderDetailB2BLinesInnerShipmentDetailsInnerCarrierDetailsInnerTrackingDetailsInnerTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for OrderDetailB2BLinesInnerShipmentDetailsInnerCarrierDetailsInnerTrackingDetailsInner
        //private OrderDetailB2BLinesInnerShipmentDetailsInnerCarrierDetailsInnerTrackingDetailsInner instance;

        public OrderDetailB2BLinesInnerShipmentDetailsInnerCarrierDetailsInnerTrackingDetailsInnerTests()
        {
            // TODO uncomment below to create an instance of OrderDetailB2BLinesInnerShipmentDetailsInnerCarrierDetailsInnerTrackingDetailsInner
            //instance = new OrderDetailB2BLinesInnerShipmentDetailsInnerCarrierDetailsInnerTrackingDetailsInner();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of OrderDetailB2BLinesInnerShipmentDetailsInnerCarrierDetailsInnerTrackingDetailsInner
        /// </summary>
        [Fact]
        public void OrderDetailB2BLinesInnerShipmentDetailsInnerCarrierDetailsInnerTrackingDetailsInnerInstanceTest()
        {
            // TODO uncomment below to test "IsType" OrderDetailB2BLinesInnerShipmentDetailsInnerCarrierDetailsInnerTrackingDetailsInner
            //Assert.IsType<OrderDetailB2BLinesInnerShipmentDetailsInnerCarrierDetailsInnerTrackingDetailsInner>(instance);
        }

        /// <summary>
        /// Test the property 'TrackingNumber'
        /// </summary>
        [Fact]
        public void TrackingNumberTest()
        {
            // TODO unit test for the property 'TrackingNumber'
        }

        /// <summary>
        /// Test the property 'TrackingUrl'
        /// </summary>
        [Fact]
        public void TrackingUrlTest()
        {
            // TODO unit test for the property 'TrackingUrl'
        }

        /// <summary>
        /// Test the property 'PackageWeight'
        /// </summary>
        [Fact]
        public void PackageWeightTest()
        {
            // TODO unit test for the property 'PackageWeight'
        }

        /// <summary>
        /// Test the property 'CartonNumber'
        /// </summary>
        [Fact]
        public void CartonNumberTest()
        {
            // TODO unit test for the property 'CartonNumber'
        }

        /// <summary>
        /// Test the property 'QuantityInBox'
        /// </summary>
        [Fact]
        public void QuantityInBoxTest()
        {
            // TODO unit test for the property 'QuantityInBox'
        }

        /// <summary>
        /// Test the property 'SerialNumbers'
        /// </summary>
        [Fact]
        public void SerialNumbersTest()
        {
            // TODO unit test for the property 'SerialNumbers'
        }
    }
}
