/*
 * XI Sdk Resellers
 *
 * For Resellers seeking to innovate with Ingram Micro API solutions, automate your eCommerce experience with our array of APIs and webhooks to craft a seamless journey for your customers.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using xi.sdk.resellers.Model;
using xi.sdk.resellers.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace xi.sdk.resellers.Test.Model
{
    /// <summary>
    ///  Class for testing OrderCreateV7RequestVmfAdditionalAttributesInner
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class OrderCreateV7RequestVmfAdditionalAttributesInnerTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for OrderCreateV7RequestVmfAdditionalAttributesInner
        //private OrderCreateV7RequestVmfAdditionalAttributesInner instance;

        public OrderCreateV7RequestVmfAdditionalAttributesInnerTests()
        {
            // TODO uncomment below to create an instance of OrderCreateV7RequestVmfAdditionalAttributesInner
            //instance = new OrderCreateV7RequestVmfAdditionalAttributesInner();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of OrderCreateV7RequestVmfAdditionalAttributesInner
        /// </summary>
        [Fact]
        public void OrderCreateV7RequestVmfAdditionalAttributesInnerInstanceTest()
        {
            // TODO uncomment below to test "IsType" OrderCreateV7RequestVmfAdditionalAttributesInner
            //Assert.IsType<OrderCreateV7RequestVmfAdditionalAttributesInner>(instance);
        }

        /// <summary>
        /// Test the property 'AttributeName'
        /// </summary>
        [Fact]
        public void AttributeNameTest()
        {
            // TODO unit test for the property 'AttributeName'
        }

        /// <summary>
        /// Test the property 'AttributeValue'
        /// </summary>
        [Fact]
        public void AttributeValueTest()
        {
            // TODO unit test for the property 'AttributeValue'
        }
    }
}
