/*
 * XI Sdk Resellers
 *
 * For Resellers seeking to innovate with Ingram Micro API solutions, automate your eCommerce experience with our array of API's and webhooks to craft a seamless journey for your customers.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using xi.sdk.resellers.Model;
using xi.sdk.resellers.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace xi.sdk.resellers.Test.Model
{
    /// <summary>
    ///  Class for testing OrderDetailB2BLinesInnerEstimatedDatesInner
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class OrderDetailB2BLinesInnerEstimatedDatesInnerTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for OrderDetailB2BLinesInnerEstimatedDatesInner
        //private OrderDetailB2BLinesInnerEstimatedDatesInner instance;

        public OrderDetailB2BLinesInnerEstimatedDatesInnerTests()
        {
            // TODO uncomment below to create an instance of OrderDetailB2BLinesInnerEstimatedDatesInner
            //instance = new OrderDetailB2BLinesInnerEstimatedDatesInner();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of OrderDetailB2BLinesInnerEstimatedDatesInner
        /// </summary>
        [Fact]
        public void OrderDetailB2BLinesInnerEstimatedDatesInnerInstanceTest()
        {
            // TODO uncomment below to test "IsType" OrderDetailB2BLinesInnerEstimatedDatesInner
            //Assert.IsType<OrderDetailB2BLinesInnerEstimatedDatesInner>(instance);
        }

        /// <summary>
        /// Test the property 'Ship'
        /// </summary>
        [Fact]
        public void ShipTest()
        {
            // TODO unit test for the property 'Ship'
        }

        /// <summary>
        /// Test the property 'Delivery'
        /// </summary>
        [Fact]
        public void DeliveryTest()
        {
            // TODO unit test for the property 'Delivery'
        }
    }
}
