/*
 * XI Sdk Resellers
 *
 * For Resellers seeking to innovate with Ingram Micro APIs solutions, automate your eCommerce experience with our array of API's and webhooks to craft a seamless journey for your customers.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using xi.sdk.resellers.Model;
using xi.sdk.resellers.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace xi.sdk.resellers.Test.Model
{
    /// <summary>
    ///  Class for testing OrderStatusAsyncNotificationRequestResourceInnerLinesInner
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class OrderStatusAsyncNotificationRequestResourceInnerLinesInnerTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for OrderStatusAsyncNotificationRequestResourceInnerLinesInner
        //private OrderStatusAsyncNotificationRequestResourceInnerLinesInner instance;

        public OrderStatusAsyncNotificationRequestResourceInnerLinesInnerTests()
        {
            // TODO uncomment below to create an instance of OrderStatusAsyncNotificationRequestResourceInnerLinesInner
            //instance = new OrderStatusAsyncNotificationRequestResourceInnerLinesInner();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of OrderStatusAsyncNotificationRequestResourceInnerLinesInner
        /// </summary>
        [Fact]
        public void OrderStatusAsyncNotificationRequestResourceInnerLinesInnerInstanceTest()
        {
            // TODO uncomment below to test "IsType" OrderStatusAsyncNotificationRequestResourceInnerLinesInner
            //Assert.IsType<OrderStatusAsyncNotificationRequestResourceInnerLinesInner>(instance);
        }

        /// <summary>
        /// Test the property 'LineNumber'
        /// </summary>
        [Fact]
        public void LineNumberTest()
        {
            // TODO unit test for the property 'LineNumber'
        }

        /// <summary>
        /// Test the property 'SubOrderNumber'
        /// </summary>
        [Fact]
        public void SubOrderNumberTest()
        {
            // TODO unit test for the property 'SubOrderNumber'
        }

        /// <summary>
        /// Test the property 'LineStatus'
        /// </summary>
        [Fact]
        public void LineStatusTest()
        {
            // TODO unit test for the property 'LineStatus'
        }

        /// <summary>
        /// Test the property 'IngramPartNumber'
        /// </summary>
        [Fact]
        public void IngramPartNumberTest()
        {
            // TODO unit test for the property 'IngramPartNumber'
        }

        /// <summary>
        /// Test the property 'VendorPartNumber'
        /// </summary>
        [Fact]
        public void VendorPartNumberTest()
        {
            // TODO unit test for the property 'VendorPartNumber'
        }

        /// <summary>
        /// Test the property 'RequestedQuantity'
        /// </summary>
        [Fact]
        public void RequestedQuantityTest()
        {
            // TODO unit test for the property 'RequestedQuantity'
        }

        /// <summary>
        /// Test the property 'ShippedQuantity'
        /// </summary>
        [Fact]
        public void ShippedQuantityTest()
        {
            // TODO unit test for the property 'ShippedQuantity'
        }

        /// <summary>
        /// Test the property 'BackorderedQuantity'
        /// </summary>
        [Fact]
        public void BackorderedQuantityTest()
        {
            // TODO unit test for the property 'BackorderedQuantity'
        }

        /// <summary>
        /// Test the property 'ShipmentDetails'
        /// </summary>
        [Fact]
        public void ShipmentDetailsTest()
        {
            // TODO unit test for the property 'ShipmentDetails'
        }

        /// <summary>
        /// Test the property 'SerialNumberDetails'
        /// </summary>
        [Fact]
        public void SerialNumberDetailsTest()
        {
            // TODO unit test for the property 'SerialNumberDetails'
        }
    }
}
