/*
 * XI Sdk Resellers
 *
 * For Resellers seeking to innovate with Ingram Micro API solutions, automate your eCommerce experience with our array of APIs and webhooks to craft a seamless journey for your customers.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using xi.sdk.resellers.Model;
using xi.sdk.resellers.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace xi.sdk.resellers.Test.Model
{
    /// <summary>
    ///  Class for testing OrderModifyResponseLinesInner
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class OrderModifyResponseLinesInnerTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for OrderModifyResponseLinesInner
        //private OrderModifyResponseLinesInner instance;

        public OrderModifyResponseLinesInnerTests()
        {
            // TODO uncomment below to create an instance of OrderModifyResponseLinesInner
            //instance = new OrderModifyResponseLinesInner();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of OrderModifyResponseLinesInner
        /// </summary>
        [Fact]
        public void OrderModifyResponseLinesInnerInstanceTest()
        {
            // TODO uncomment below to test "IsType" OrderModifyResponseLinesInner
            //Assert.IsType<OrderModifyResponseLinesInner>(instance);
        }

        /// <summary>
        /// Test the property 'SubOrderNumber'
        /// </summary>
        [Fact]
        public void SubOrderNumberTest()
        {
            // TODO unit test for the property 'SubOrderNumber'
        }

        /// <summary>
        /// Test the property 'IngramLineNumber'
        /// </summary>
        [Fact]
        public void IngramLineNumberTest()
        {
            // TODO unit test for the property 'IngramLineNumber'
        }

        /// <summary>
        /// Test the property 'CustomerLineNumber'
        /// </summary>
        [Fact]
        public void CustomerLineNumberTest()
        {
            // TODO unit test for the property 'CustomerLineNumber'
        }

        /// <summary>
        /// Test the property 'IngramPartNumber'
        /// </summary>
        [Fact]
        public void IngramPartNumberTest()
        {
            // TODO unit test for the property 'IngramPartNumber'
        }

        /// <summary>
        /// Test the property 'VendorPartNumber'
        /// </summary>
        [Fact]
        public void VendorPartNumberTest()
        {
            // TODO unit test for the property 'VendorPartNumber'
        }

        /// <summary>
        /// Test the property 'QuantityOrdered'
        /// </summary>
        [Fact]
        public void QuantityOrderedTest()
        {
            // TODO unit test for the property 'QuantityOrdered'
        }

        /// <summary>
        /// Test the property 'QuantityConfirmed'
        /// </summary>
        [Fact]
        public void QuantityConfirmedTest()
        {
            // TODO unit test for the property 'QuantityConfirmed'
        }

        /// <summary>
        /// Test the property 'QuantityBackOrdered'
        /// </summary>
        [Fact]
        public void QuantityBackOrderedTest()
        {
            // TODO unit test for the property 'QuantityBackOrdered'
        }

        /// <summary>
        /// Test the property 'ShipmentDetails'
        /// </summary>
        [Fact]
        public void ShipmentDetailsTest()
        {
            // TODO unit test for the property 'ShipmentDetails'
        }

        /// <summary>
        /// Test the property 'AdditionalAttributes'
        /// </summary>
        [Fact]
        public void AdditionalAttributesTest()
        {
            // TODO unit test for the property 'AdditionalAttributes'
        }

        /// <summary>
        /// Test the property 'Notes'
        /// </summary>
        [Fact]
        public void NotesTest()
        {
            // TODO unit test for the property 'Notes'
        }
    }
}
