/*
 * XI Sdk Resellers
 *
 * For Resellers seeking to innovate with Ingram Micro API solutions, automate your eCommerce experience with our array of API's and webhooks to craft a seamless journey for your customers.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using xi.sdk.resellers.Model;
using xi.sdk.resellers.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace xi.sdk.resellers.Test.Model
{
    /// <summary>
    ///  Class for testing OrderCreateResponseOrdersInnerLinesInnerShipmentDetailsInner
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class OrderCreateResponseOrdersInnerLinesInnerShipmentDetailsInnerTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for OrderCreateResponseOrdersInnerLinesInnerShipmentDetailsInner
        //private OrderCreateResponseOrdersInnerLinesInnerShipmentDetailsInner instance;

        public OrderCreateResponseOrdersInnerLinesInnerShipmentDetailsInnerTests()
        {
            // TODO uncomment below to create an instance of OrderCreateResponseOrdersInnerLinesInnerShipmentDetailsInner
            //instance = new OrderCreateResponseOrdersInnerLinesInnerShipmentDetailsInner();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of OrderCreateResponseOrdersInnerLinesInnerShipmentDetailsInner
        /// </summary>
        [Fact]
        public void OrderCreateResponseOrdersInnerLinesInnerShipmentDetailsInnerInstanceTest()
        {
            // TODO uncomment below to test "IsType" OrderCreateResponseOrdersInnerLinesInnerShipmentDetailsInner
            //Assert.IsType<OrderCreateResponseOrdersInnerLinesInnerShipmentDetailsInner>(instance);
        }

        /// <summary>
        /// Test the property 'CarrierCode'
        /// </summary>
        [Fact]
        public void CarrierCodeTest()
        {
            // TODO unit test for the property 'CarrierCode'
        }

        /// <summary>
        /// Test the property 'CarrierName'
        /// </summary>
        [Fact]
        public void CarrierNameTest()
        {
            // TODO unit test for the property 'CarrierName'
        }

        /// <summary>
        /// Test the property 'ShipFromWarehouseId'
        /// </summary>
        [Fact]
        public void ShipFromWarehouseIdTest()
        {
            // TODO unit test for the property 'ShipFromWarehouseId'
        }

        /// <summary>
        /// Test the property 'ShipFromLocation'
        /// </summary>
        [Fact]
        public void ShipFromLocationTest()
        {
            // TODO unit test for the property 'ShipFromLocation'
        }

        /// <summary>
        /// Test the property 'FreightAccountNumber'
        /// </summary>
        [Fact]
        public void FreightAccountNumberTest()
        {
            // TODO unit test for the property 'FreightAccountNumber'
        }

        /// <summary>
        /// Test the property 'SignatureRequired'
        /// </summary>
        [Fact]
        public void SignatureRequiredTest()
        {
            // TODO unit test for the property 'SignatureRequired'
        }

        /// <summary>
        /// Test the property 'ShippingInstructions'
        /// </summary>
        [Fact]
        public void ShippingInstructionsTest()
        {
            // TODO unit test for the property 'ShippingInstructions'
        }
    }
}
