/*
 * XI Sdk Resellers
 *
 * For Resellers seeking to innovate with Ingram Micro APIs solutions, automate your eCommerce experience with our array of API's and webhooks to craft a seamless journey for your customers.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using xi.sdk.resellers.Model;
using xi.sdk.resellers.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace xi.sdk.resellers.Test.Model
{
    /// <summary>
    ///  Class for testing OrderCreateV7RequestVmfVendorAdditionalAttributesInner
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class OrderCreateV7RequestVmfVendorAdditionalAttributesInnerTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for OrderCreateV7RequestVmfVendorAdditionalAttributesInner
        //private OrderCreateV7RequestVmfVendorAdditionalAttributesInner instance;

        public OrderCreateV7RequestVmfVendorAdditionalAttributesInnerTests()
        {
            // TODO uncomment below to create an instance of OrderCreateV7RequestVmfVendorAdditionalAttributesInner
            //instance = new OrderCreateV7RequestVmfVendorAdditionalAttributesInner();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of OrderCreateV7RequestVmfVendorAdditionalAttributesInner
        /// </summary>
        [Fact]
        public void OrderCreateV7RequestVmfVendorAdditionalAttributesInnerInstanceTest()
        {
            // TODO uncomment below to test "IsType" OrderCreateV7RequestVmfVendorAdditionalAttributesInner
            //Assert.IsType<OrderCreateV7RequestVmfVendorAdditionalAttributesInner>(instance);
        }

        /// <summary>
        /// Test the property 'VendorName'
        /// </summary>
        [Fact]
        public void VendorNameTest()
        {
            // TODO unit test for the property 'VendorName'
        }

        /// <summary>
        /// Test the property 'ProductId'
        /// </summary>
        [Fact]
        public void ProductIdTest()
        {
            // TODO unit test for the property 'ProductId'
        }

        /// <summary>
        /// Test the property 'AdditionalAttributes'
        /// </summary>
        [Fact]
        public void AdditionalAttributesTest()
        {
            // TODO unit test for the property 'AdditionalAttributes'
        }
    }
}
