/*
 * XI Sdk Resellers
 *
 * For Resellers seeking to innovate with Ingram Micro API solutions, automate your eCommerce experience with our array of API's and webhooks to craft a seamless journey for your customers.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using xi.sdk.resellers.Model;
using xi.sdk.resellers.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace xi.sdk.resellers.Test.Model
{
    /// <summary>
    ///  Class for testing OrderCreateV7ResponseResource
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class OrderCreateV7ResponseResourceTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for OrderCreateV7ResponseResource
        //private OrderCreateV7ResponseResource instance;

        public OrderCreateV7ResponseResourceTests()
        {
            // TODO uncomment below to create an instance of OrderCreateV7ResponseResource
            //instance = new OrderCreateV7ResponseResource();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of OrderCreateV7ResponseResource
        /// </summary>
        [Fact]
        public void OrderCreateV7ResponseResourceInstanceTest()
        {
            // TODO uncomment below to test "IsType" OrderCreateV7ResponseResource
            //Assert.IsType<OrderCreateV7ResponseResource>(instance);
        }

        /// <summary>
        /// Test the property 'CustomerOrderNumber'
        /// </summary>
        [Fact]
        public void CustomerOrderNumberTest()
        {
            // TODO unit test for the property 'CustomerOrderNumber'
        }

        /// <summary>
        /// Test the property 'BillToAddressId'
        /// </summary>
        [Fact]
        public void BillToAddressIdTest()
        {
            // TODO unit test for the property 'BillToAddressId'
        }

        /// <summary>
        /// Test the property 'OrderSplit'
        /// </summary>
        [Fact]
        public void OrderSplitTest()
        {
            // TODO unit test for the property 'OrderSplit'
        }

        /// <summary>
        /// Test the property 'ProcessedPartially'
        /// </summary>
        [Fact]
        public void ProcessedPartiallyTest()
        {
            // TODO unit test for the property 'ProcessedPartially'
        }

        /// <summary>
        /// Test the property 'PurchaseOrderTotal'
        /// </summary>
        [Fact]
        public void PurchaseOrderTotalTest()
        {
            // TODO unit test for the property 'PurchaseOrderTotal'
        }

        /// <summary>
        /// Test the property 'ShipToInfo'
        /// </summary>
        [Fact]
        public void ShipToInfoTest()
        {
            // TODO unit test for the property 'ShipToInfo'
        }

        /// <summary>
        /// Test the property 'Orders'
        /// </summary>
        [Fact]
        public void OrdersTest()
        {
            // TODO unit test for the property 'Orders'
        }
    }
}
