/*
 * XI Sdk Resellers
 *
 * For Resellers seeking to innovate with Ingram Micro API solutions, automate your eCommerce experience with our array of APIs and webhooks to craft a seamless journey for your customers.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using xi.sdk.resellers.Model;
using xi.sdk.resellers.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace xi.sdk.resellers.Test.Model
{
    /// <summary>
    ///  Class for testing PriceAndAvailabilityResponseInnerReserveInventoryDetailsInner
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PriceAndAvailabilityResponseInnerReserveInventoryDetailsInnerTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PriceAndAvailabilityResponseInnerReserveInventoryDetailsInner
        //private PriceAndAvailabilityResponseInnerReserveInventoryDetailsInner instance;

        public PriceAndAvailabilityResponseInnerReserveInventoryDetailsInnerTests()
        {
            // TODO uncomment below to create an instance of PriceAndAvailabilityResponseInnerReserveInventoryDetailsInner
            //instance = new PriceAndAvailabilityResponseInnerReserveInventoryDetailsInner();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PriceAndAvailabilityResponseInnerReserveInventoryDetailsInner
        /// </summary>
        [Fact]
        public void PriceAndAvailabilityResponseInnerReserveInventoryDetailsInnerInstanceTest()
        {
            // TODO uncomment below to test "IsType" PriceAndAvailabilityResponseInnerReserveInventoryDetailsInner
            //Assert.IsType<PriceAndAvailabilityResponseInnerReserveInventoryDetailsInner>(instance);
        }

        /// <summary>
        /// Test the property 'QuantityReserved'
        /// </summary>
        [Fact]
        public void QuantityReservedTest()
        {
            // TODO unit test for the property 'QuantityReserved'
        }

        /// <summary>
        /// Test the property 'QuantityAvailable'
        /// </summary>
        [Fact]
        public void QuantityAvailableTest()
        {
            // TODO unit test for the property 'QuantityAvailable'
        }

        /// <summary>
        /// Test the property 'Effectivedate'
        /// </summary>
        [Fact]
        public void EffectivedateTest()
        {
            // TODO unit test for the property 'Effectivedate'
        }

        /// <summary>
        /// Test the property 'Expirydate'
        /// </summary>
        [Fact]
        public void ExpirydateTest()
        {
            // TODO unit test for the property 'Expirydate'
        }
    }
}
