/*
 * XI Sdk Resellers
 *
 * For Resellers seeking to innovate with Ingram Micro API solutions, automate your eCommerce experience with our array of APIs and webhooks to craft a seamless journey for your customers.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using xi.sdk.resellers.Model;
using xi.sdk.resellers.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace xi.sdk.resellers.Test.Model
{
    /// <summary>
    ///  Class for testing PriceAndAvailabilityResponseInnerSubscriptionPriceInnerOptionsInnerResourcePricingInner
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PriceAndAvailabilityResponseInnerSubscriptionPriceInnerOptionsInnerResourcePricingInnerTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PriceAndAvailabilityResponseInnerSubscriptionPriceInnerOptionsInnerResourcePricingInner
        //private PriceAndAvailabilityResponseInnerSubscriptionPriceInnerOptionsInnerResourcePricingInner instance;

        public PriceAndAvailabilityResponseInnerSubscriptionPriceInnerOptionsInnerResourcePricingInnerTests()
        {
            // TODO uncomment below to create an instance of PriceAndAvailabilityResponseInnerSubscriptionPriceInnerOptionsInnerResourcePricingInner
            //instance = new PriceAndAvailabilityResponseInnerSubscriptionPriceInnerOptionsInnerResourcePricingInner();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PriceAndAvailabilityResponseInnerSubscriptionPriceInnerOptionsInnerResourcePricingInner
        /// </summary>
        [Fact]
        public void PriceAndAvailabilityResponseInnerSubscriptionPriceInnerOptionsInnerResourcePricingInnerInstanceTest()
        {
            // TODO uncomment below to test "IsType" PriceAndAvailabilityResponseInnerSubscriptionPriceInnerOptionsInnerResourcePricingInner
            //Assert.IsType<PriceAndAvailabilityResponseInnerSubscriptionPriceInnerOptionsInnerResourcePricingInner>(instance);
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }

        /// <summary>
        /// Test the property 'Quantity'
        /// </summary>
        [Fact]
        public void QuantityTest()
        {
            // TODO unit test for the property 'Quantity'
        }

        /// <summary>
        /// Test the property 'Msrp'
        /// </summary>
        [Fact]
        public void MsrpTest()
        {
            // TODO unit test for the property 'Msrp'
        }

        /// <summary>
        /// Test the property 'UnitPrice'
        /// </summary>
        [Fact]
        public void UnitPriceTest()
        {
            // TODO unit test for the property 'UnitPrice'
        }

        /// <summary>
        /// Test the property 'Margin'
        /// </summary>
        [Fact]
        public void MarginTest()
        {
            // TODO unit test for the property 'Margin'
        }

        /// <summary>
        /// Test the property 'CurrencyCode'
        /// </summary>
        [Fact]
        public void CurrencyCodeTest()
        {
            // TODO unit test for the property 'CurrencyCode'
        }

        /// <summary>
        /// Test the property 'SubscriptionPeriod'
        /// </summary>
        [Fact]
        public void SubscriptionPeriodTest()
        {
            // TODO unit test for the property 'SubscriptionPeriod'
        }
    }
}
