/*
 * XI Sdk Resellers
 *
 * For Resellers seeking to innovate with Ingram Micro API solutions, automate your eCommerce experience with our array of API's and webhooks to craft a seamless journey for your customers.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using xi.sdk.resellers.Model;
using xi.sdk.resellers.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace xi.sdk.resellers.Test.Model
{
    /// <summary>
    ///  Class for testing PriceAndAvailabilityResponseInnerSubscriptionPriceInnerBillingPeriod
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PriceAndAvailabilityResponseInnerSubscriptionPriceInnerBillingPeriodTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PriceAndAvailabilityResponseInnerSubscriptionPriceInnerBillingPeriod
        //private PriceAndAvailabilityResponseInnerSubscriptionPriceInnerBillingPeriod instance;

        public PriceAndAvailabilityResponseInnerSubscriptionPriceInnerBillingPeriodTests()
        {
            // TODO uncomment below to create an instance of PriceAndAvailabilityResponseInnerSubscriptionPriceInnerBillingPeriod
            //instance = new PriceAndAvailabilityResponseInnerSubscriptionPriceInnerBillingPeriod();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PriceAndAvailabilityResponseInnerSubscriptionPriceInnerBillingPeriod
        /// </summary>
        [Fact]
        public void PriceAndAvailabilityResponseInnerSubscriptionPriceInnerBillingPeriodInstanceTest()
        {
            // TODO uncomment below to test "IsType" PriceAndAvailabilityResponseInnerSubscriptionPriceInnerBillingPeriod
            //Assert.IsType<PriceAndAvailabilityResponseInnerSubscriptionPriceInnerBillingPeriod>(instance);
        }

        /// <summary>
        /// Test the property 'BillingPeriodUnit'
        /// </summary>
        [Fact]
        public void BillingPeriodUnitTest()
        {
            // TODO unit test for the property 'BillingPeriodUnit'
        }

        /// <summary>
        /// Test the property 'BillingPeriod'
        /// </summary>
        [Fact]
        public void BillingPeriodTest()
        {
            // TODO unit test for the property 'BillingPeriod'
        }
    }
}
