/*
 * XI Sdk Resellers
 *
 * For Resellers seeking to innovate with Ingram Micro API solutions, automate your eCommerce experience with our array of API's and webhooks to craft a seamless journey for your customers.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using xi.sdk.resellers.Model;
using xi.sdk.resellers.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace xi.sdk.resellers.Test.Model
{
    /// <summary>
    ///  Class for testing ProductSearchResponseSubscriptionCatalogInner
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ProductSearchResponseSubscriptionCatalogInnerTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ProductSearchResponseSubscriptionCatalogInner
        //private ProductSearchResponseSubscriptionCatalogInner instance;

        public ProductSearchResponseSubscriptionCatalogInnerTests()
        {
            // TODO uncomment below to create an instance of ProductSearchResponseSubscriptionCatalogInner
            //instance = new ProductSearchResponseSubscriptionCatalogInner();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ProductSearchResponseSubscriptionCatalogInner
        /// </summary>
        [Fact]
        public void ProductSearchResponseSubscriptionCatalogInnerInstanceTest()
        {
            // TODO uncomment below to test "IsType" ProductSearchResponseSubscriptionCatalogInner
            //Assert.IsType<ProductSearchResponseSubscriptionCatalogInner>(instance);
        }

        /// <summary>
        /// Test the property 'GroupName'
        /// </summary>
        [Fact]
        public void GroupNameTest()
        {
            // TODO unit test for the property 'GroupName'
        }

        /// <summary>
        /// Test the property 'GroupDescription'
        /// </summary>
        [Fact]
        public void GroupDescriptionTest()
        {
            // TODO unit test for the property 'GroupDescription'
        }

        /// <summary>
        /// Test the property 'NumberOfPlans'
        /// </summary>
        [Fact]
        public void NumberOfPlansTest()
        {
            // TODO unit test for the property 'NumberOfPlans'
        }

        /// <summary>
        /// Test the property 'Link'
        /// </summary>
        [Fact]
        public void LinkTest()
        {
            // TODO unit test for the property 'Link'
        }

        /// <summary>
        /// Test the property 'Plans'
        /// </summary>
        [Fact]
        public void PlansTest()
        {
            // TODO unit test for the property 'Plans'
        }
    }
}
