/*
 * XI Sdk Resellers
 *
 * For Resellers seeking to innovate with Ingram Micro API solutions, automate your eCommerce experience with our array of API's and webhooks to craft a seamless journey for your customers.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using xi.sdk.resellers.Model;
using xi.sdk.resellers.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace xi.sdk.resellers.Test.Model
{
    /// <summary>
    ///  Class for testing ProductSearchResponseCatalogInner
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ProductSearchResponseCatalogInnerTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ProductSearchResponseCatalogInner
        //private ProductSearchResponseCatalogInner instance;

        public ProductSearchResponseCatalogInnerTests()
        {
            // TODO uncomment below to create an instance of ProductSearchResponseCatalogInner
            //instance = new ProductSearchResponseCatalogInner();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ProductSearchResponseCatalogInner
        /// </summary>
        [Fact]
        public void ProductSearchResponseCatalogInnerInstanceTest()
        {
            // TODO uncomment below to test "IsType" ProductSearchResponseCatalogInner
            //Assert.IsType<ProductSearchResponseCatalogInner>(instance);
        }

        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Fact]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }

        /// <summary>
        /// Test the property 'Category'
        /// </summary>
        [Fact]
        public void CategoryTest()
        {
            // TODO unit test for the property 'Category'
        }

        /// <summary>
        /// Test the property 'SubCategory'
        /// </summary>
        [Fact]
        public void SubCategoryTest()
        {
            // TODO unit test for the property 'SubCategory'
        }

        /// <summary>
        /// Test the property 'ProductType'
        /// </summary>
        [Fact]
        public void ProductTypeTest()
        {
            // TODO unit test for the property 'ProductType'
        }

        /// <summary>
        /// Test the property 'IngramPartNumber'
        /// </summary>
        [Fact]
        public void IngramPartNumberTest()
        {
            // TODO unit test for the property 'IngramPartNumber'
        }

        /// <summary>
        /// Test the property 'VendorPartNumber'
        /// </summary>
        [Fact]
        public void VendorPartNumberTest()
        {
            // TODO unit test for the property 'VendorPartNumber'
        }

        /// <summary>
        /// Test the property 'UpcCode'
        /// </summary>
        [Fact]
        public void UpcCodeTest()
        {
            // TODO unit test for the property 'UpcCode'
        }

        /// <summary>
        /// Test the property 'VendorName'
        /// </summary>
        [Fact]
        public void VendorNameTest()
        {
            // TODO unit test for the property 'VendorName'
        }

        /// <summary>
        /// Test the property 'EndUserRequired'
        /// </summary>
        [Fact]
        public void EndUserRequiredTest()
        {
            // TODO unit test for the property 'EndUserRequired'
        }

        /// <summary>
        /// Test the property 'HasDiscounts'
        /// </summary>
        [Fact]
        public void HasDiscountsTest()
        {
            // TODO unit test for the property 'HasDiscounts'
        }

        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Fact]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }

        /// <summary>
        /// Test the property 'Discontinued'
        /// </summary>
        [Fact]
        public void DiscontinuedTest()
        {
            // TODO unit test for the property 'Discontinued'
        }

        /// <summary>
        /// Test the property 'NewProduct'
        /// </summary>
        [Fact]
        public void NewProductTest()
        {
            // TODO unit test for the property 'NewProduct'
        }

        /// <summary>
        /// Test the property 'DirectShip'
        /// </summary>
        [Fact]
        public void DirectShipTest()
        {
            // TODO unit test for the property 'DirectShip'
        }

        /// <summary>
        /// Test the property 'HasWarranty'
        /// </summary>
        [Fact]
        public void HasWarrantyTest()
        {
            // TODO unit test for the property 'HasWarranty'
        }

        /// <summary>
        /// Test the property 'ExtraDescription'
        /// </summary>
        [Fact]
        public void ExtraDescriptionTest()
        {
            // TODO unit test for the property 'ExtraDescription'
        }

        /// <summary>
        /// Test the property 'ReplacementSku'
        /// </summary>
        [Fact]
        public void ReplacementSkuTest()
        {
            // TODO unit test for the property 'ReplacementSku'
        }

        /// <summary>
        /// Test the property 'AuthorizedToPurchase'
        /// </summary>
        [Fact]
        public void AuthorizedToPurchaseTest()
        {
            // TODO unit test for the property 'AuthorizedToPurchase'
        }

        /// <summary>
        /// Test the property 'IsMsrpVisible'
        /// </summary>
        [Fact]
        public void IsMsrpVisibleTest()
        {
            // TODO unit test for the property 'IsMsrpVisible'
        }

        /// <summary>
        /// Test the property 'IsPriceVisible'
        /// </summary>
        [Fact]
        public void IsPriceVisibleTest()
        {
            // TODO unit test for the property 'IsPriceVisible'
        }

        /// <summary>
        /// Test the property 'CustomerAuthorization'
        /// </summary>
        [Fact]
        public void CustomerAuthorizationTest()
        {
            // TODO unit test for the property 'CustomerAuthorization'
        }

        /// <summary>
        /// Test the property 'SkuAvailableInFeed'
        /// </summary>
        [Fact]
        public void SkuAvailableInFeedTest()
        {
            // TODO unit test for the property 'SkuAvailableInFeed'
        }

        /// <summary>
        /// Test the property 'Msrpvisibleorg'
        /// </summary>
        [Fact]
        public void MsrpvisibleorgTest()
        {
            // TODO unit test for the property 'Msrpvisibleorg'
        }

        /// <summary>
        /// Test the property 'Pricevisibleorg'
        /// </summary>
        [Fact]
        public void PricevisibleorgTest()
        {
            // TODO unit test for the property 'Pricevisibleorg'
        }

        /// <summary>
        /// Test the property 'Intorderableorg'
        /// </summary>
        [Fact]
        public void IntorderableorgTest()
        {
            // TODO unit test for the property 'Intorderableorg'
        }

        /// <summary>
        /// Test the property 'Nonintorderableorg'
        /// </summary>
        [Fact]
        public void NonintorderableorgTest()
        {
            // TODO unit test for the property 'Nonintorderableorg'
        }

        /// <summary>
        /// Test the property 'Webvisibleorg'
        /// </summary>
        [Fact]
        public void WebvisibleorgTest()
        {
            // TODO unit test for the property 'Webvisibleorg'
        }

        /// <summary>
        /// Test the property 'Links'
        /// </summary>
        [Fact]
        public void LinksTest()
        {
            // TODO unit test for the property 'Links'
        }
    }
}
