/*
 * XI Sdk Resellers
 *
 * For Resellers seeking to innovate with Ingram Micro APIs solutions, automate your eCommerce experience with our array of API's and webhooks to craft a seamless journey for your customers.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using xi.sdk.resellers.Model;
using xi.sdk.resellers.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace xi.sdk.resellers.Test.Model
{
    /// <summary>
    ///  Class for testing QuoteSearchResponseQuotesInnerLinks
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class QuoteSearchResponseQuotesInnerLinksTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for QuoteSearchResponseQuotesInnerLinks
        //private QuoteSearchResponseQuotesInnerLinks instance;

        public QuoteSearchResponseQuotesInnerLinksTests()
        {
            // TODO uncomment below to create an instance of QuoteSearchResponseQuotesInnerLinks
            //instance = new QuoteSearchResponseQuotesInnerLinks();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of QuoteSearchResponseQuotesInnerLinks
        /// </summary>
        [Fact]
        public void QuoteSearchResponseQuotesInnerLinksInstanceTest()
        {
            // TODO uncomment below to test "IsType" QuoteSearchResponseQuotesInnerLinks
            //Assert.IsType<QuoteSearchResponseQuotesInnerLinks>(instance);
        }

        /// <summary>
        /// Test the property 'Topic'
        /// </summary>
        [Fact]
        public void TopicTest()
        {
            // TODO unit test for the property 'Topic'
        }

        /// <summary>
        /// Test the property 'Href'
        /// </summary>
        [Fact]
        public void HrefTest()
        {
            // TODO unit test for the property 'Href'
        }

        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Fact]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }
    }
}
