/*
 * XI Sdk Resellers
 *
 * For Resellers seeking to innovate with Ingram Micro API solutions, automate your eCommerce experience with our array of APIs and webhooks to craft a seamless journey for your customers.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using xi.sdk.resellers.Model;
using xi.sdk.resellers.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace xi.sdk.resellers.Test.Model
{
    /// <summary>
    ///  Class for testing RenewalsSearchRequestStatus
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class RenewalsSearchRequestStatusTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for RenewalsSearchRequestStatus
        //private RenewalsSearchRequestStatus instance;

        public RenewalsSearchRequestStatusTests()
        {
            // TODO uncomment below to create an instance of RenewalsSearchRequestStatus
            //instance = new RenewalsSearchRequestStatus();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of RenewalsSearchRequestStatus
        /// </summary>
        [Fact]
        public void RenewalsSearchRequestStatusInstanceTest()
        {
            // TODO uncomment below to test "IsType" RenewalsSearchRequestStatus
            //Assert.IsType<RenewalsSearchRequestStatus>(instance);
        }

        /// <summary>
        /// Test the property 'OpporutinyStatus'
        /// </summary>
        [Fact]
        public void OpporutinyStatusTest()
        {
            // TODO unit test for the property 'OpporutinyStatus'
        }
    }
}
