/*
 * XI Sdk Resellers
 *
 * For Resellers seeking to innovate with Ingram Micro APIs solutions, automate your eCommerce experience with our array of API's and webhooks to craft a seamless journey for your customers.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using xi.sdk.resellers.Model;
using xi.sdk.resellers.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace xi.sdk.resellers.Test.Model
{
    /// <summary>
    ///  Class for testing RenewalsSearchRequestDateTypeInvoiceDate
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class RenewalsSearchRequestDateTypeInvoiceDateTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for RenewalsSearchRequestDateTypeInvoiceDate
        //private RenewalsSearchRequestDateTypeInvoiceDate instance;

        public RenewalsSearchRequestDateTypeInvoiceDateTests()
        {
            // TODO uncomment below to create an instance of RenewalsSearchRequestDateTypeInvoiceDate
            //instance = new RenewalsSearchRequestDateTypeInvoiceDate();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of RenewalsSearchRequestDateTypeInvoiceDate
        /// </summary>
        [Fact]
        public void RenewalsSearchRequestDateTypeInvoiceDateInstanceTest()
        {
            // TODO uncomment below to test "IsType" RenewalsSearchRequestDateTypeInvoiceDate
            //Assert.IsType<RenewalsSearchRequestDateTypeInvoiceDate>(instance);
        }

        /// <summary>
        /// Test the property 'CustomStartDate'
        /// </summary>
        [Fact]
        public void CustomStartDateTest()
        {
            // TODO unit test for the property 'CustomStartDate'
        }

        /// <summary>
        /// Test the property 'CustomEndDate'
        /// </summary>
        [Fact]
        public void CustomEndDateTest()
        {
            // TODO unit test for the property 'CustomEndDate'
        }
    }
}
