/*
 * XI Sdk Resellers
 *
 * For Resellers seeking to innovate with Ingram Micro API solutions, automate your eCommerce experience with our array of API's and webhooks to craft a seamless journey for your customers.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using xi.sdk.resellers.Model;
using xi.sdk.resellers.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace xi.sdk.resellers.Test.Model
{
    /// <summary>
    ///  Class for testing VendorRequiredInforesponseInner
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class VendorRequiredInforesponseInnerTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for VendorRequiredInforesponseInner
        //private VendorRequiredInforesponseInner instance;

        public VendorRequiredInforesponseInnerTests()
        {
            // TODO uncomment below to create an instance of VendorRequiredInforesponseInner
            //instance = new VendorRequiredInforesponseInner();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of VendorRequiredInforesponseInner
        /// </summary>
        [Fact]
        public void VendorRequiredInforesponseInnerInstanceTest()
        {
            // TODO uncomment below to test "IsType" VendorRequiredInforesponseInner
            //Assert.IsType<VendorRequiredInforesponseInner>(instance);
        }

        /// <summary>
        /// Test the property 'QuoteNumber'
        /// </summary>
        [Fact]
        public void QuoteNumberTest()
        {
            // TODO unit test for the property 'QuoteNumber'
        }

        /// <summary>
        /// Test the property 'IngramPartNumber'
        /// </summary>
        [Fact]
        public void IngramPartNumberTest()
        {
            // TODO unit test for the property 'IngramPartNumber'
        }

        /// <summary>
        /// Test the property 'VendorPartNumber'
        /// </summary>
        [Fact]
        public void VendorPartNumberTest()
        {
            // TODO unit test for the property 'VendorPartNumber'
        }

        /// <summary>
        /// Test the property 'PlanId'
        /// </summary>
        [Fact]
        public void PlanIdTest()
        {
            // TODO unit test for the property 'PlanId'
        }

        /// <summary>
        /// Test the property 'PlanName'
        /// </summary>
        [Fact]
        public void PlanNameTest()
        {
            // TODO unit test for the property 'PlanName'
        }

        /// <summary>
        /// Test the property 'ResponseMessages'
        /// </summary>
        [Fact]
        public void ResponseMessagesTest()
        {
            // TODO unit test for the property 'ResponseMessages'
        }

        /// <summary>
        /// Test the property 'VmfAdditionalAttributes'
        /// </summary>
        [Fact]
        public void VmfAdditionalAttributesTest()
        {
            // TODO unit test for the property 'VmfAdditionalAttributes'
        }

        /// <summary>
        /// Test the property 'VriAdditionalAttributes'
        /// </summary>
        [Fact]
        public void VriAdditionalAttributesTest()
        {
            // TODO unit test for the property 'VriAdditionalAttributes'
        }
    }
}
