/*
 * XI Sdk Resellers
 *
 * For Resellers seeking to innovate with Ingram Micro API solutions, automate your eCommerce experience with our array of APIs and webhooks to craft a seamless journey for your customers.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = xi.sdk.resellers.Client.FileParameter;
using OpenAPIDateConverter = xi.sdk.resellers.Client.OpenAPIDateConverter;

namespace xi.sdk.resellers.Model
{
    /// <summary>
    /// OrderCreateV7RequestVmfVendorAdditionalAttributesInnerAdditionalAttributesInnerChoicesInnerChoicesInner
    /// </summary>
    [DataContract(Name = "order_create_v7_request_vmfVendorAdditionalAttributes_inner_additionalAttributes_inner_choices_inner_choices_inner")]
    public partial class OrderCreateV7RequestVmfVendorAdditionalAttributesInnerAdditionalAttributesInnerChoicesInnerChoicesInner : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="OrderCreateV7RequestVmfVendorAdditionalAttributesInnerAdditionalAttributesInnerChoicesInnerChoicesInner" /> class.
        /// </summary>
        /// <param name="attributename">The name of the vendor mandatory field.</param>
        /// <param name="attributeValue">The value of the vendor mandatory field.</param>
        public OrderCreateV7RequestVmfVendorAdditionalAttributesInnerAdditionalAttributesInnerChoicesInnerChoicesInner(string attributename = default, string attributeValue = default)
        {
            this.Attributename = attributename;
            this.AttributeValue = attributeValue;
        }

        /// <summary>
        /// The name of the vendor mandatory field
        /// </summary>
        /// <value>The name of the vendor mandatory field</value>
        [DataMember(Name = "attributename", EmitDefaultValue = false)]
        public string Attributename { get; set; }

        /// <summary>
        /// The value of the vendor mandatory field
        /// </summary>
        /// <value>The value of the vendor mandatory field</value>
        [DataMember(Name = "attributeValue", EmitDefaultValue = false)]
        public string AttributeValue { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class OrderCreateV7RequestVmfVendorAdditionalAttributesInnerAdditionalAttributesInnerChoicesInnerChoicesInner {\n");
            sb.Append("  Attributename: ").Append(Attributename).Append("\n");
            sb.Append("  AttributeValue: ").Append(AttributeValue).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
