/*
 * XI Sdk Resellers
 *
 * For Resellers seeking to innovate with Ingram Micro APIs solutions, automate your eCommerce experience with our array of API's and webhooks to craft a seamless journey for your customers.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = xi.sdk.resellers.Client.FileParameter;
using OpenAPIDateConverter = xi.sdk.resellers.Client.OpenAPIDateConverter;

namespace xi.sdk.resellers.Model
{
    /// <summary>
    /// The shipping information provided by the reseller.
    /// </summary>
    [DataContract(Name = "order_create_v7_request_shipToInfo")]
    public partial class OrderCreateV7RequestShipToInfo : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="OrderCreateV7RequestShipToInfo" /> class.
        /// </summary>
        /// <param name="addressId">The ID references the resellers address in Ingram Micro&#39;s system for shipping. Provided to resellers during the onboarding process..</param>
        /// <param name="contact">The company contact provided by the reseller..</param>
        /// <param name="companyName">The reseller&#39;s company name or the End-User&#39;s Name.</param>
        /// <param name="addressLine1">The street address and building or house number the order will be shipped to..</param>
        /// <param name="addressLine2">The apartment number the order will be shipped to..</param>
        /// <param name="city">The city the order will be shipped to..</param>
        /// <param name="state">The state the order will be shipped to..</param>
        /// <param name="postalCode">End User Name.</param>
        /// <param name="countryCode">The zip or postal code the order will be shipped to..</param>
        /// <param name="email">The company contact email address..</param>
        /// <param name="shippingNotes">shippingNotes.</param>
        /// <param name="phoneNumber">The company contact phone number..</param>
        public OrderCreateV7RequestShipToInfo(string addressId = default, string contact = default, string companyName = default, string addressLine1 = default, string addressLine2 = default, string city = default, string state = default, string postalCode = default, string countryCode = default, string email = default, string shippingNotes = default, string phoneNumber = default)
        {
            this.AddressId = addressId;
            this.Contact = contact;
            this.CompanyName = companyName;
            this.AddressLine1 = addressLine1;
            this.AddressLine2 = addressLine2;
            this.City = city;
            this.State = state;
            this.PostalCode = postalCode;
            this.CountryCode = countryCode;
            this.Email = email;
            this.ShippingNotes = shippingNotes;
            this.PhoneNumber = phoneNumber;
        }

        /// <summary>
        /// The ID references the resellers address in Ingram Micro&#39;s system for shipping. Provided to resellers during the onboarding process.
        /// </summary>
        /// <value>The ID references the resellers address in Ingram Micro&#39;s system for shipping. Provided to resellers during the onboarding process.</value>
        [DataMember(Name = "addressId", EmitDefaultValue = false)]
        public string AddressId { get; set; }

        /// <summary>
        /// The company contact provided by the reseller.
        /// </summary>
        /// <value>The company contact provided by the reseller.</value>
        [DataMember(Name = "contact", EmitDefaultValue = true)]
        public string Contact { get; set; }

        /// <summary>
        /// The reseller&#39;s company name or the End-User&#39;s Name
        /// </summary>
        /// <value>The reseller&#39;s company name or the End-User&#39;s Name</value>
        [DataMember(Name = "companyName", EmitDefaultValue = true)]
        public string CompanyName { get; set; }

        /// <summary>
        /// The street address and building or house number the order will be shipped to.
        /// </summary>
        /// <value>The street address and building or house number the order will be shipped to.</value>
        [DataMember(Name = "addressLine1", EmitDefaultValue = true)]
        public string AddressLine1 { get; set; }

        /// <summary>
        /// The apartment number the order will be shipped to.
        /// </summary>
        /// <value>The apartment number the order will be shipped to.</value>
        [DataMember(Name = "addressLine2", EmitDefaultValue = true)]
        public string AddressLine2 { get; set; }

        /// <summary>
        /// The city the order will be shipped to.
        /// </summary>
        /// <value>The city the order will be shipped to.</value>
        [DataMember(Name = "city", EmitDefaultValue = true)]
        public string City { get; set; }

        /// <summary>
        /// The state the order will be shipped to.
        /// </summary>
        /// <value>The state the order will be shipped to.</value>
        [DataMember(Name = "state", EmitDefaultValue = true)]
        public string State { get; set; }

        /// <summary>
        /// End User Name
        /// </summary>
        /// <value>End User Name</value>
        [DataMember(Name = "postalCode", EmitDefaultValue = true)]
        public string PostalCode { get; set; }

        /// <summary>
        /// The zip or postal code the order will be shipped to.
        /// </summary>
        /// <value>The zip or postal code the order will be shipped to.</value>
        [DataMember(Name = "countryCode", EmitDefaultValue = true)]
        public string CountryCode { get; set; }

        /// <summary>
        /// The company contact email address.
        /// </summary>
        /// <value>The company contact email address.</value>
        [DataMember(Name = "email", EmitDefaultValue = true)]
        public string Email { get; set; }

        /// <summary>
        /// Gets or Sets ShippingNotes
        /// </summary>
        [DataMember(Name = "shippingNotes", EmitDefaultValue = true)]
        public string ShippingNotes { get; set; }

        /// <summary>
        /// The company contact phone number.
        /// </summary>
        /// <value>The company contact phone number.</value>
        [DataMember(Name = "phoneNumber", EmitDefaultValue = true)]
        public string PhoneNumber { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class OrderCreateV7RequestShipToInfo {\n");
            sb.Append("  AddressId: ").Append(AddressId).Append("\n");
            sb.Append("  Contact: ").Append(Contact).Append("\n");
            sb.Append("  CompanyName: ").Append(CompanyName).Append("\n");
            sb.Append("  AddressLine1: ").Append(AddressLine1).Append("\n");
            sb.Append("  AddressLine2: ").Append(AddressLine2).Append("\n");
            sb.Append("  City: ").Append(City).Append("\n");
            sb.Append("  State: ").Append(State).Append("\n");
            sb.Append("  PostalCode: ").Append(PostalCode).Append("\n");
            sb.Append("  CountryCode: ").Append(CountryCode).Append("\n");
            sb.Append("  Email: ").Append(Email).Append("\n");
            sb.Append("  ShippingNotes: ").Append(ShippingNotes).Append("\n");
            sb.Append("  PhoneNumber: ").Append(PhoneNumber).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // AddressId (string) maxLength
            if (this.AddressId != null && this.AddressId.Length > 10)
            {
                yield return new ValidationResult("Invalid value for AddressId, length must be less than 10.", new [] { "AddressId" });
            }

            // Contact (string) maxLength
            if (this.Contact != null && this.Contact.Length > 70)
            {
                yield return new ValidationResult("Invalid value for Contact, length must be less than 70.", new [] { "Contact" });
            }

            // CompanyName (string) maxLength
            if (this.CompanyName != null && this.CompanyName.Length > 40)
            {
                yield return new ValidationResult("Invalid value for CompanyName, length must be less than 40.", new [] { "CompanyName" });
            }

            // AddressLine1 (string) maxLength
            if (this.AddressLine1 != null && this.AddressLine1.Length > 70)
            {
                yield return new ValidationResult("Invalid value for AddressLine1, length must be less than 70.", new [] { "AddressLine1" });
            }

            // AddressLine2 (string) maxLength
            if (this.AddressLine2 != null && this.AddressLine2.Length > 70)
            {
                yield return new ValidationResult("Invalid value for AddressLine2, length must be less than 70.", new [] { "AddressLine2" });
            }

            // City (string) maxLength
            if (this.City != null && this.City.Length > 25)
            {
                yield return new ValidationResult("Invalid value for City, length must be less than 25.", new [] { "City" });
            }

            // State (string) maxLength
            if (this.State != null && this.State.Length > 3)
            {
                yield return new ValidationResult("Invalid value for State, length must be less than 3.", new [] { "State" });
            }

            // CountryCode (string) maxLength
            if (this.CountryCode != null && this.CountryCode.Length > 10)
            {
                yield return new ValidationResult("Invalid value for CountryCode, length must be less than 10.", new [] { "CountryCode" });
            }

            yield break;
        }
    }

}
