/*
 * XI Sdk Resellers
 *
 * For Resellers seeking to innovate with Ingram Micro API solutions, automate your eCommerce experience with our array of APIs and webhooks to craft a seamless journey for your customers.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = xi.sdk.resellers.Client.FileParameter;
using OpenAPIDateConverter = xi.sdk.resellers.Client.OpenAPIDateConverter;

namespace xi.sdk.resellers.Model
{
    /// <summary>
    /// Serial information of the hardware to be associated with the warranty, applicable on post sale orders.
    /// </summary>
    [DataContract(Name = "order_create_v7_request_lines_inner_warrantyInfo_serialInfo_inner")]
    public partial class OrderCreateV7RequestLinesInnerWarrantyInfoSerialInfoInner : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="OrderCreateV7RequestLinesInnerWarrantyInfoSerialInfoInner" /> class.
        /// </summary>
        /// <param name="dateOfPurchase">Date of purchase of the hardware..</param>
        /// <param name="shipDate">Vendor specific mandatory field, date of hardware/product shipment from vendor..</param>
        /// <param name="primarySerialNumber">Serial number of the hardware/product..</param>
        /// <param name="secondarySerialNumber">Serial number of accessory associated with the above hardware/product..</param>
        public OrderCreateV7RequestLinesInnerWarrantyInfoSerialInfoInner(string dateOfPurchase = default, string shipDate = default, string primarySerialNumber = default, string secondarySerialNumber = default)
        {
            this.DateOfPurchase = dateOfPurchase;
            this.ShipDate = shipDate;
            this.PrimarySerialNumber = primarySerialNumber;
            this.SecondarySerialNumber = secondarySerialNumber;
        }

        /// <summary>
        /// Date of purchase of the hardware.
        /// </summary>
        /// <value>Date of purchase of the hardware.</value>
        [DataMember(Name = "dateOfPurchase", EmitDefaultValue = false)]
        public string DateOfPurchase { get; set; }

        /// <summary>
        /// Vendor specific mandatory field, date of hardware/product shipment from vendor.
        /// </summary>
        /// <value>Vendor specific mandatory field, date of hardware/product shipment from vendor.</value>
        [DataMember(Name = "shipDate", EmitDefaultValue = false)]
        public string ShipDate { get; set; }

        /// <summary>
        /// Serial number of the hardware/product.
        /// </summary>
        /// <value>Serial number of the hardware/product.</value>
        [DataMember(Name = "primarySerialNumber", EmitDefaultValue = false)]
        public string PrimarySerialNumber { get; set; }

        /// <summary>
        /// Serial number of accessory associated with the above hardware/product.
        /// </summary>
        /// <value>Serial number of accessory associated with the above hardware/product.</value>
        [DataMember(Name = "secondarySerialNumber", EmitDefaultValue = false)]
        public string SecondarySerialNumber { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class OrderCreateV7RequestLinesInnerWarrantyInfoSerialInfoInner {\n");
            sb.Append("  DateOfPurchase: ").Append(DateOfPurchase).Append("\n");
            sb.Append("  ShipDate: ").Append(ShipDate).Append("\n");
            sb.Append("  PrimarySerialNumber: ").Append(PrimarySerialNumber).Append("\n");
            sb.Append("  SecondarySerialNumber: ").Append(SecondarySerialNumber).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // DateOfPurchase (string) maxLength
            if (this.DateOfPurchase != null && this.DateOfPurchase.Length > 8)
            {
                yield return new ValidationResult("Invalid value for DateOfPurchase, length must be less than 8.", new [] { "DateOfPurchase" });
            }

            // ShipDate (string) maxLength
            if (this.ShipDate != null && this.ShipDate.Length > 8)
            {
                yield return new ValidationResult("Invalid value for ShipDate, length must be less than 8.", new [] { "ShipDate" });
            }

            yield break;
        }
    }

}
