/*
 * XI Sdk Resellers
 *
 * For Resellers seeking to innovate with Ingram Micro API solutions, automate your eCommerce experience with our array of API's and webhooks to craft a seamless journey for your customers.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = xi.sdk.resellers.Client.FileParameter;
using OpenAPIDateConverter = xi.sdk.resellers.Client.OpenAPIDateConverter;

namespace xi.sdk.resellers.Model
{
    /// <summary>
    /// OrderCreateRequestLinesInnerWarrantyInfoInnerSerialInfoInner
    /// </summary>
    [DataContract(Name = "OrderCreateRequest_lines_inner_warrantyInfo_inner_serialInfo_inner")]
    public partial class OrderCreateRequestLinesInnerWarrantyInfoInnerSerialInfoInner : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="OrderCreateRequestLinesInnerWarrantyInfoInnerSerialInfoInner" /> class.
        /// </summary>
        /// <param name="dateofPurchase">Date of purchase of the hardware..</param>
        /// <param name="shipDate">Vendor specific mandatory field, date of hardware/product shipment from vendor..</param>
        /// <param name="primarySerialNumber">Serial number of the hardware/product..</param>
        /// <param name="secondarySerialNumber">Serial number of accessory associated with the above hardware/product..</param>
        public OrderCreateRequestLinesInnerWarrantyInfoInnerSerialInfoInner(DateOnly dateofPurchase = default, DateOnly shipDate = default, string primarySerialNumber = default, string secondarySerialNumber = default)
        {
            this.DateofPurchase = dateofPurchase;
            this.ShipDate = shipDate;
            this.PrimarySerialNumber = primarySerialNumber;
            this.SecondarySerialNumber = secondarySerialNumber;
        }

        /// <summary>
        /// Date of purchase of the hardware.
        /// </summary>
        /// <value>Date of purchase of the hardware.</value>
        [DataMember(Name = "dateofPurchase", EmitDefaultValue = false)]
        public DateOnly DateofPurchase { get; set; }

        /// <summary>
        /// Vendor specific mandatory field, date of hardware/product shipment from vendor.
        /// </summary>
        /// <value>Vendor specific mandatory field, date of hardware/product shipment from vendor.</value>
        [DataMember(Name = "shipDate", EmitDefaultValue = false)]
        public DateOnly ShipDate { get; set; }

        /// <summary>
        /// Serial number of the hardware/product.
        /// </summary>
        /// <value>Serial number of the hardware/product.</value>
        [DataMember(Name = "primarySerialNumber", EmitDefaultValue = false)]
        public string PrimarySerialNumber { get; set; }

        /// <summary>
        /// Serial number of accessory associated with the above hardware/product.
        /// </summary>
        /// <value>Serial number of accessory associated with the above hardware/product.</value>
        [DataMember(Name = "secondarySerialNumber", EmitDefaultValue = false)]
        public string SecondarySerialNumber { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class OrderCreateRequestLinesInnerWarrantyInfoInnerSerialInfoInner {\n");
            sb.Append("  DateofPurchase: ").Append(DateofPurchase).Append("\n");
            sb.Append("  ShipDate: ").Append(ShipDate).Append("\n");
            sb.Append("  PrimarySerialNumber: ").Append(PrimarySerialNumber).Append("\n");
            sb.Append("  SecondarySerialNumber: ").Append(SecondarySerialNumber).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
