/*
 * XI Sdk Resellers
 *
 * For Resellers seeking to innovate with Ingram Micro's API solutions, automate your eCommerce experience with our array of API's and webhooks to craft a seamless journey for your customers.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = xi.sdk.resellers.Client.FileParameter;
using OpenAPIDateConverter = xi.sdk.resellers.Client.OpenAPIDateConverter;

namespace xi.sdk.resellers.Model
{
    /// <summary>
    /// ValidateQuoteResponse
    /// </summary>
    [DataContract(Name = "ValidateQuoteResponse")]
    public partial class ValidateQuoteResponse : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ValidateQuoteResponse" /> class.
        /// </summary>
        /// <param name="quoteNumber">A unique identifier generated by Ingram Micro&#39;s CRM specific to each quote..</param>
        /// <param name="vendorName">The name of the vendor..</param>
        /// <param name="vmfAdditionalAttributes">The object containing the list of fields required at a header level by the vendor..</param>
        /// <param name="lines">The object containing the lines from the quote..</param>
        /// <param name="quoteType">quoteType.</param>
        /// <param name="vendorGroupName">vendorGroupName.</param>
        /// <param name="vendorQuoteNumber">vendorQuoteNumber.</param>
        /// <param name="vendorMasterNumber">vendorMasterNumber.</param>
        public ValidateQuoteResponse(string quoteNumber = default, string vendorName = default, List<ValidateQuoteResponseVmfAdditionalAttributesInner> vmfAdditionalAttributes = default, List<ValidateQuoteResponseLinesInner> lines = default, int quoteType = default, string vendorGroupName = default, string vendorQuoteNumber = default, string vendorMasterNumber = default)
        {
            this.QuoteNumber = quoteNumber;
            this.VendorName = vendorName;
            this.VmfAdditionalAttributes = vmfAdditionalAttributes;
            this.Lines = lines;
            this.QuoteType = quoteType;
            this.VendorGroupName = vendorGroupName;
            this.VendorQuoteNumber = vendorQuoteNumber;
            this.VendorMasterNumber = vendorMasterNumber;
        }

        /// <summary>
        /// A unique identifier generated by Ingram Micro&#39;s CRM specific to each quote.
        /// </summary>
        /// <value>A unique identifier generated by Ingram Micro&#39;s CRM specific to each quote.</value>
        /*
        <example>QUO-14551943-D2Y9L9</example>
        */
        [DataMember(Name = "quoteNumber", EmitDefaultValue = false)]
        public string QuoteNumber { get; set; }

        /// <summary>
        /// The name of the vendor.
        /// </summary>
        /// <value>The name of the vendor.</value>
        /*
        <example>Cisco</example>
        */
        [DataMember(Name = "vendorName", EmitDefaultValue = false)]
        public string VendorName { get; set; }

        /// <summary>
        /// The object containing the list of fields required at a header level by the vendor.
        /// </summary>
        /// <value>The object containing the list of fields required at a header level by the vendor.</value>
        [DataMember(Name = "vmfAdditionalAttributes", EmitDefaultValue = false)]
        public List<ValidateQuoteResponseVmfAdditionalAttributesInner> VmfAdditionalAttributes { get; set; }

        /// <summary>
        /// The object containing the lines from the quote.
        /// </summary>
        /// <value>The object containing the lines from the quote.</value>
        [DataMember(Name = "lines", EmitDefaultValue = false)]
        public List<ValidateQuoteResponseLinesInner> Lines { get; set; }

        /// <summary>
        /// Gets or Sets QuoteType
        /// </summary>
        [DataMember(Name = "quoteType", EmitDefaultValue = false)]
        public int QuoteType { get; set; }

        /// <summary>
        /// Gets or Sets VendorGroupName
        /// </summary>
        [DataMember(Name = "vendorGroupName", EmitDefaultValue = false)]
        public string VendorGroupName { get; set; }

        /// <summary>
        /// Gets or Sets VendorQuoteNumber
        /// </summary>
        [DataMember(Name = "vendorQuoteNumber", EmitDefaultValue = false)]
        public string VendorQuoteNumber { get; set; }

        /// <summary>
        /// Gets or Sets VendorMasterNumber
        /// </summary>
        [DataMember(Name = "vendorMasterNumber", EmitDefaultValue = false)]
        public string VendorMasterNumber { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ValidateQuoteResponse {\n");
            sb.Append("  QuoteNumber: ").Append(QuoteNumber).Append("\n");
            sb.Append("  VendorName: ").Append(VendorName).Append("\n");
            sb.Append("  VmfAdditionalAttributes: ").Append(VmfAdditionalAttributes).Append("\n");
            sb.Append("  Lines: ").Append(Lines).Append("\n");
            sb.Append("  QuoteType: ").Append(QuoteType).Append("\n");
            sb.Append("  VendorGroupName: ").Append(VendorGroupName).Append("\n");
            sb.Append("  VendorQuoteNumber: ").Append(VendorQuoteNumber).Append("\n");
            sb.Append("  VendorMasterNumber: ").Append(VendorMasterNumber).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
