/*
 * XI Sdk Resellers
 *
 * For Resellers seeking to innovate with Ingram Micro APIs solutions, automate your eCommerce experience with our array of API's and webhooks to craft a seamless journey for your customers.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = xi.sdk.resellers.Client.FileParameter;
using OpenAPIDateConverter = xi.sdk.resellers.Client.OpenAPIDateConverter;

namespace xi.sdk.resellers.Model
{
    /// <summary>
    /// VendorRequiredInforesponseInner
    /// </summary>
    [DataContract(Name = "VendorRequiredInforesponse_inner")]
    public partial class VendorRequiredInforesponseInner : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="VendorRequiredInforesponseInner" /> class.
        /// </summary>
        /// <param name="quoteNumber">A unique identifier generated by Ingram Micro&#39;s CRM specific to each quote..</param>
        /// <param name="ingramPartNumber">The unique IngramMicro part number..</param>
        /// <param name="vendorPartNumber">The vendor&#39;s part number for the line item..</param>
        /// <param name="planId">ID of the subscription plan.</param>
        /// <param name="planName">Name of the subscription plan.</param>
        /// <param name="responseMessages">responseMessages.</param>
        /// <param name="vmfAdditionalAttributes">vmfAdditionalAttributes.</param>
        /// <param name="vriAdditionalAttributes">vriAdditionalAttributes.</param>
        public VendorRequiredInforesponseInner(string quoteNumber = default, string ingramPartNumber = default, string vendorPartNumber = default, string planId = default, string planName = default, List<VendorRequiredInforesponseInnerResponseMessagesInner> responseMessages = default, List<VendorRequiredInforesponseInnerVmfAdditionalAttributesInner> vmfAdditionalAttributes = default, List<VendorRequiredInforesponseInnerVmfAdditionalAttributesInnerAdditionalAttributesInner> vriAdditionalAttributes = default)
        {
            this.QuoteNumber = quoteNumber;
            this.IngramPartNumber = ingramPartNumber;
            this.VendorPartNumber = vendorPartNumber;
            this.PlanId = planId;
            this.PlanName = planName;
            this.ResponseMessages = responseMessages;
            this.VmfAdditionalAttributes = vmfAdditionalAttributes;
            this.VriAdditionalAttributes = vriAdditionalAttributes;
        }

        /// <summary>
        /// A unique identifier generated by Ingram Micro&#39;s CRM specific to each quote.
        /// </summary>
        /// <value>A unique identifier generated by Ingram Micro&#39;s CRM specific to each quote.</value>
        /*
        <example>quoteNumber&#x3D;QUO-14551943-D2Y9L9</example>
        */
        [DataMember(Name = "quoteNumber", EmitDefaultValue = false)]
        public string QuoteNumber { get; set; }

        /// <summary>
        /// The unique IngramMicro part number.
        /// </summary>
        /// <value>The unique IngramMicro part number.</value>
        [DataMember(Name = "ingramPartNumber", EmitDefaultValue = false)]
        public string IngramPartNumber { get; set; }

        /// <summary>
        /// The vendor&#39;s part number for the line item.
        /// </summary>
        /// <value>The vendor&#39;s part number for the line item.</value>
        [DataMember(Name = "vendorPartNumber", EmitDefaultValue = false)]
        public string VendorPartNumber { get; set; }

        /// <summary>
        /// ID of the subscription plan
        /// </summary>
        /// <value>ID of the subscription plan</value>
        [DataMember(Name = "planId", EmitDefaultValue = false)]
        public string PlanId { get; set; }

        /// <summary>
        /// Name of the subscription plan
        /// </summary>
        /// <value>Name of the subscription plan</value>
        [DataMember(Name = "planName", EmitDefaultValue = false)]
        public string PlanName { get; set; }

        /// <summary>
        /// Gets or Sets ResponseMessages
        /// </summary>
        [DataMember(Name = "responseMessages", EmitDefaultValue = false)]
        public List<VendorRequiredInforesponseInnerResponseMessagesInner> ResponseMessages { get; set; }

        /// <summary>
        /// Gets or Sets VmfAdditionalAttributes
        /// </summary>
        [DataMember(Name = "vmfAdditionalAttributes", EmitDefaultValue = false)]
        public List<VendorRequiredInforesponseInnerVmfAdditionalAttributesInner> VmfAdditionalAttributes { get; set; }

        /// <summary>
        /// Gets or Sets VriAdditionalAttributes
        /// </summary>
        [DataMember(Name = "vriAdditionalAttributes", EmitDefaultValue = false)]
        public List<VendorRequiredInforesponseInnerVmfAdditionalAttributesInnerAdditionalAttributesInner> VriAdditionalAttributes { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class VendorRequiredInforesponseInner {\n");
            sb.Append("  QuoteNumber: ").Append(QuoteNumber).Append("\n");
            sb.Append("  IngramPartNumber: ").Append(IngramPartNumber).Append("\n");
            sb.Append("  VendorPartNumber: ").Append(VendorPartNumber).Append("\n");
            sb.Append("  PlanId: ").Append(PlanId).Append("\n");
            sb.Append("  PlanName: ").Append(PlanName).Append("\n");
            sb.Append("  ResponseMessages: ").Append(ResponseMessages).Append("\n");
            sb.Append("  VmfAdditionalAttributes: ").Append(VmfAdditionalAttributes).Append("\n");
            sb.Append("  VriAdditionalAttributes: ").Append(VriAdditionalAttributes).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
